{
 "title": "MSTeams Connect",
 "description": "A dashboard for use with the Mattermost MSTeams Connect plugin.",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace" },
   {
    "name": "top_plugin_api_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(mattermost_plugin_api_time_count{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\"}[${__range_s}s])) by (api_name)))"
    }
   },
   {
    "name": "top_plugin_api_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(mattermost_plugin_api_time_sum{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\"}[${__range_s}s])) by (api_name) / sum(increase(mattermost_plugin_api_time_count{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\"}[${__range_s}s])) by (api_name)))"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "top_db_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_db_store_time_count{namespace=\"$namespace\"}[${__range_s}s])) by (method)))"
    }
   },
   {
    "name": "top_db_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_db_store_time_sum{namespace=\"$namespace\"}[${__range_s}s])) by (method) / sum(increase(msteams_connect_db_store_time_count{namespace=\"$namespace\"}[${__range_s}s])) by (method)))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected Users",
   "type": "stat",
   "description": "The total number of Mattermost users connected to MS Teams users.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(msteams_connect_app_connected_users_total{namespace=~\"$namespace\"})",
     "legendFormat": "Connected Users"
    }
   ]
  },
  {
   "title": "Synthetic Users",
   "type": "stat",
   "description": "The total number of synthetic users.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(msteams_connect_app_synthetic_users_total{namespace=~\"$namespace\"})",
     "legendFormat": "Synthetic Users"
    }
   ]
  },
  {
   "title": "Linked Channels",
   "type": "stat",
   "description": "The total number of linked channels to MS Teams.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(msteams_connect_app_linked_channels_total{namespace=~\"$namespace\"})",
     "legendFormat": "Linked Channels"
    }
   ]
  },
  {
   "title": "MS Teams Users",
   "type": "stat",
   "description": "The total number of MS Teams users detected upstream during the sync job.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(msteams_connect_app_upstream_users{namespace=~\"$namespace\"})",
     "legendFormat": "Linked Channels"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(up{namespace=~\"$namespace\", endpoint=\"msteamsmetrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "DB Calls (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_db_store_time_count{namespace=\"$namespace\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(msteams_connect_db_store_time_count{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "HTTP Requests (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(msteams_connect_http_requests_total{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "Requests ({{instance}})"
    },
    {
     "expr": "sum(rate(msteams_connect_http_requests_total{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Requests (Total)"
    },
    {
     "expr": "rate(msteams_connect_http_errors_total{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "Errors ({{instance}})"
    },
    {
     "expr": "sum(rate(msteams_connect_http_errors_total{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Errors (Total)"
    }
   ]
  },
  {
   "title": "Store Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_db_store_time_bucket{namespace=\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p99 ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_db_store_time_bucket{namespace=\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p50 ({{instance}})"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_api_time_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p99 ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_api_time_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p50 ({{instance}})"
    }
   ]
  },
  {
   "title": "DB Calls by Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_db_store_time_count{namespace=\"$namespace\",method=~\"$top_db_count\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Requests by Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_api_time_count{namespace=~\"$namespace\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "DB calls by duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_db_store_time_sum{namespace=\"$namespace\",method=~\"$top_db_latency\"}[5m])) by (method) / sum(increase(msteams_connect_db_store_time_count{namespace=\"$namespace\",method=~\"$top_db_latency\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Requests by Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_api_time_sum{namespace=~\"$namespace\"}[5m])) by (handler) / sum(increase(msteams_connect_api_time_count{namespace=~\"$namespace\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "MS Graph API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "MS Graph Client Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_count{namespace=~\"$namespace\",success=\"true\"}[5m])) by (instance)",
     "legendFormat": "Requests ({{instance}})"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_count{namespace=~\"$namespace\",success!=\"true\"}[5m])) by (instance)",
     "legendFormat": "Errors ({{instance}})"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_count{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests (Errors Only)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_count{namespace=~\"$namespace\",success!=\"true\"}[5m])) by (instance)",
     "legendFormat": "Errors ({{instance}})"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_count{namespace=~\"$namespace\",success!=\"true\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests by Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_count{namespace=~\"$namespace\"}[5m])) by (method)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "MS Graph Client Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_msgraph_client_time_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p99 ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_msgraph_client_time_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p50 ({{instance}})"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests by Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_sum{namespace=~\"$namespace\"}[5m])) by (method) / sum(increase(msteams_connect_msgraph_client_time_count{namespace=~\"$namespace\"}[5m])) by (method)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Change Event Queue",
   "type": "timeseries",
   "description": "The number of events currently in the change event queue and awaiting processing by an available goroutine.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_app_change_event_queue_length{namespace=\"$namespace\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Processed Change Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_processed_change_event_total{namespace=\"$namespace\",discarded_reason=\"\"}[5m])) by (change_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded Change Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_processed_change_event_total{namespace=\"$namespace\",discarded_reason!=\"\"}[5m])) by (discarded_reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Lifecycle Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_lifecycle_event_total{namespace=\"$namespace\"}[5m])) by (event_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded Lifecycle Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Subscriptions (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 94 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_subscriptions_count{namespace=\"$namespace\"}[5m])) by (action)",
     "legendFormat": "{{action}}"
    },
    {
     "expr": "sum(rate(msteams_connect_events_subscriptions_count{namespace=\"$namespace\",source=\"msteams\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Messages (Mattermost -> MSTeams, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_messages_count{namespace=\"$namespace\",source=\"mattermost\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_count{namespace=\"$namespace\",source=\"mattermost\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_count{namespace=\"$namespace\",source=\"mattermost\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Messages (MSTeams -> Mattermost, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_messages_count{namespace=\"$namespace\",source=\"msteams\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_count{namespace=\"$namespace\",source=\"msteams\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_count{namespace=\"$namespace\",source=\"msteams\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Reactions (Mattermost -> MSTeams, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_reactions_count{namespace=\"$namespace\",source=\"mattermost\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_count{namespace=\"$namespace\",source=\"mattermost\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_count{namespace=\"$namespace\",source=\"mattermost\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Reactions (MSTeams -> Mattermost, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_reactions_count{namespace=\"$namespace\",source=\"msteams\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_count{namespace=\"$namespace\",source=\"msteams\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_count{namespace=\"$namespace\",source=\"msteams\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Files (Mattermost -> MSTeams, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_files_count{namespace=\"$namespace\",source=\"mattermost\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_count{namespace=\"$namespace\",source=\"mattermost\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_count{namespace=\"$namespace\",source=\"mattermost\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Files (MSTeams -> Mattermost, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_files_count{namespace=\"$namespace\",source=\"msteams\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_count{namespace=\"$namespace\",source=\"msteams\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_count{namespace=\"$namespace\",source=\"msteams\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Plugin API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 126 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 Plugin API Requests by Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(mattermost_plugin_api_time_count{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\",api_name=~\"$top_plugin_api_count\"}[5m])) by (api_name)",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Top 10 Plugin API Requests by Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(increase(mattermost_plugin_api_time_sum{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\",api_name=~\"$top_plugin_api_latency\"}[5m])) by (api_name) / sum(increase(mattermost_plugin_api_time_count{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\",api_name=~\"$top_plugin_api_latency\"}[5m])) by (api_name)",
       "legendFormat": "{{handler}}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 127 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "go_goroutines{namespace=~\"$namespace\",instance=~\".*:9094\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(go_goroutines{namespace=~\"$namespace\",instance=~\".*:9094\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Heap Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{namespace=~\"$namespace\",instance=~\".*:9094\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}