{
 "title": "MS Teams (Global)",
 "description": "A dashboard for use with the Mattermost MSTeams plugin.",
 "tags": [
  "mattermost",
  "msteams"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "top_plugin_api_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(mattermost_plugin_api_time_count{plugin_id=\"com.mattermost.msteams-sync\"}[${__range_s}s])) by (api_name)))"
    }
   },
   {
    "name": "top_plugin_api_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(mattermost_plugin_api_time_sum{plugin_id=\"com.mattermost.msteams-sync\"}[${__range_s}s])) by (api_name) / sum(increase(mattermost_plugin_api_time_count{plugin_id=\"com.mattermost.msteams-sync\"}[${__range_s}s])) by (api_name)))"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "top_db_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_db_store_time_seconds_count[${__range_s}s])) by (method)))"
    }
   },
   {
    "name": "top_db_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_db_store_time_seconds_sum[${__range_s}s])) by (method) / sum(increase(msteams_connect_db_store_time_seconds_count[${__range_s}s])) by (method)))"
    }
   },
   {
    "name": "top_msgraph_client_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_msgraph_client_time_seconds_count[${__range_s}s])) by (method)))"
    }
   },
   {
    "name": "top_msgraph_client_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_msgraph_client_time_seconds_count[${__range_s}s])) by (method)))"
    }
   }
  ]
 },
 "panels": [
  { "title": "MS Teams Plugin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT 'Global' AS Name" }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 } },
  {
   "title": "Connected Users",
   "type": "stat",
   "description": "The total number of Mattermost users connected to MS Teams users.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(msteams_connect_app_connected_users) by (namespace))",
     "legendFormat": "Connected Users"
    }
   ]
  },
  {
   "title": "Linked Channels",
   "type": "stat",
   "description": "The total number of linked channels to MS Teams.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(msteams_connect_app_linked_channels) by (namespace))",
     "legendFormat": "Linked Channels"
    }
   ]
  },
  {
   "title": "MS Teams Users",
   "type": "stat",
   "description": "The total number of MS Teams users detected upstream during the sync job.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(msteams_connect_app_upstream_users) by (namespace))",
     "legendFormat": "Linked Channels"
    }
   ]
  },
  {
   "title": "Synthetic Users",
   "type": "stat",
   "description": "The total number of synthetic users.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max(msteams_connect_app_synthetic_users) by (namespace))",
     "legendFormat": "Synthetic Users"
    }
   ]
  },
  {
   "title": "Plugin Versions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_system_plugin_info{plugin=\"msteams\"}) by (namespace, version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Next Client Secret Expiry",
   "type": "stat",
   "description": "When the next application client secret expires.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(msteams_connect_msgraph_client_secret_end_date_timestamp_seconds{plugin=\"msteams\"}  * 1000)",
     "legendFormat": "Expiry Timestamp"
    }
   ]
  },
  {
   "title": "Client Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(sum(increase(msteams_connect_msgraph_client_time_seconds_count{success!=\"true\"}[5m])) / sum(increase(msteams_connect_msgraph_client_time_seconds_count[5m])) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "DB Calls (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_db_store_time_seconds_count[5m] offset 7d)) ",
     "legendFormat": "Last Week"
    },
    {
     "expr": "sum(rate(msteams_connect_db_store_time_seconds_count[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(rate(msteams_connect_db_store_time_seconds_count[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "HTTP Requests (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_http_requests_total[5m] offset 7d))",
     "legendFormat": "Last Week"
    },
    {
     "expr": "sum(rate(msteams_connect_http_requests_total[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(rate(msteams_connect_http_requests_total[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DB Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_db_store_time_seconds_bucket[5m])) by (namespace,le))",
     "legendFormat": "p99 ({{namespace}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_db_store_time_seconds_bucket[5m])) by (namespace,le))",
     "legendFormat": "p50 ({{namespace}})"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_api_time_seconds_bucket[5m])) by (namespace,le))",
     "legendFormat": "p99 ({{namespace}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_api_time_seconds_bucket[5m])) by (namespace,le))",
     "legendFormat": "p50 ({{namespace}})"
    }
   ]
  },
  {
   "title": "DB Calls by Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_db_store_time_seconds_count{method=~\"$top_db_count\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Requests by Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_api_time_seconds_count[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "DB calls by Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_db_store_time_seconds_sum{method=~\"$top_db_latency\"}[5m])) by (method) / sum(increase(msteams_connect_db_store_time_seconds_count{method=~\"$top_db_latency\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Requests by Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_api_time_seconds_sum[5m])) by (handler) / sum(increase(msteams_connect_api_time_seconds_count[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Goroutine Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_system_plugin_goroutine_failures_total[5m])) by (namespace) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Errors (per second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_http_errors_total[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(rate(msteams_connect_http_errors_total[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(msteams_connect_http_errors_total[5m] offset 7d))",
     "legendFormat": "Last Week"
    }
   ]
  },
  { "title": "MS Graph API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "MS Graph Client Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count[5m] offset 7d))",
     "legendFormat": "Last Week"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count[5m])) by (namespace)",
     "legendFormat": "Requests ({{namespace}})"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests (Errors Only)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{success!=\"true\"}[5m])) by (namespace)",
     "legendFormat": "Errors ({{namespace}})"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{success!=\"true\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{success!=\"true\"}[5m] offset 7d))",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests by Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{method=~\"$top_msgraph_client_count\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "MS Graph Client Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_msgraph_client_time_seconds_bucket[5m])) by (namespace,le))",
     "legendFormat": "p99 ({{namespace}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_msgraph_client_time_seconds_bucket[5m])) by (namespace,le))",
     "legendFormat": "p50 ({{namespace}})"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests by Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_sum{method=~\"$top_msgraph_client_latency\"}[5m])) by (method) / sum(increase(msteams_connect_msgraph_client_time_seconds_count{method=~\"$top_msgraph_client_latency\"}[5m])) by (method)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "MS Graph Client Error Rate",
   "type": "timeseries",
   "description": "Percentage of client requests failing.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{success!=\"true\"}[5m])) / sum(increase(msteams_connect_msgraph_client_time_seconds_count[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalidated oAuth Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_oauth_token_invalidated_total[5m])) by (namespace)",
     "legendFormat": "Invalidated Tokens ({{$namespace}})"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Change Event Queue",
   "type": "timeseries",
   "description": "The number of events currently in the change event queue and awaiting processing by an available goroutine, as well as the number of events rejected because the queue was full.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_app_change_event_queue_length[5m])) by (namespace)",
     "legendFormat": "Length {{namespace}}"
    },
    {
     "expr": "sum(increase(msteams_connect_events_change_event_queue_rejected_total[5m])) by (namespace)",
     "legendFormat": "Rejected {{namespace}}"
    }
   ]
  },
  {
   "title": "Processed Change Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_change_events_total{discarded_reason=\"\"}[5m])) by (change_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded Change Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 103 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_change_events_total{discarded_reason!=\"\"}[5m])) by (discarded_reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Events Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_change_events_total{discarded_reason=\"\"}[15m])) / sum(rate(msteams_connect_events_change_events_total[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Lifecycle Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_lifecycle_events_total[5m])) by (event_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded Lifecycle Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 111 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_lifecycle_events_total{discarded_reason!=\"\"}[5m])) by (discarded_reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Events Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_lifecycle_events_total{discarded_reason=\"\"}[15m])) / sum(rate(msteams_connect_events_lifecycle_events_total[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscriptions (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_subscriptions_total[5m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Messages (Mattermost -> MSTeams, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{source=\"mattermost\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{source=\"mattermost\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{source=\"mattermost\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Messages (MSTeams -> Mattermost, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{source=\"msteams\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{source=\"msteams\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{source=\"msteams\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Reactions (Mattermost -> MSTeams, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{source=\"mattermost\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{source=\"mattermost\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{source=\"mattermost\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Reactions (MSTeams -> Mattermost, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{source=\"msteams\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{source=\"msteams\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{source=\"msteams\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Files (Mattermost -> MSTeams, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_files_total{source=\"mattermost\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_total{source=\"mattermost\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_total{source=\"mattermost\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Files (MSTeams -> Mattermost, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_files_total{source=\"msteams\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_total{source=\"msteams\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_total{source=\"msteams\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  { "title": "Plugin API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 } },
  {
   "title": "Top 10 Plugin API Requests by Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_plugin_api_time_count{plugin_id=\"com.mattermost.msteams-sync\",api_name=~\"$top_plugin_api_count\"}[5m])) by (api_name)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Top 10 Plugin API Requests by Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_plugin_api_time_sum{plugin_id=\"com.mattermost.msteams-sync\",api_name=~\"$top_plugin_api_latency\"}[5m])) by (api_name) / sum(increase(mattermost_plugin_api_time_count{plugin_id=\"com.mattermost.msteams-sync\",api_name=~\"$top_plugin_api_latency\"}[5m])) by (api_name)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "targets": [
    {
     "expr": "sum(go_goroutines{plugin=\"msteams\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    },
    {
     "expr": "sum(go_goroutines{plugin=\"msteams\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Heap Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{plugin=\"msteams\"}) by(namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "targets": [
    {
     "expr": "sum(msteams_connect_app_active_workers_total) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Workers Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_app_workers_time_seconds_bucket[5m])) by (worker,le))",
     "legendFormat": "{{worker}}, p99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_app_workers_time_seconds_bucket[5m])) by (worker,le))",
     "legendFormat": "{{worker}}, p50"
    }
   ]
  },
  {
   "title": "DB Connections (Whole Server)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mattermost_db_master_connections_total)",
     "legendFormat": "master"
    },
    {
     "expr": "sum(mattermost_db_read_replica_connections_total)",
     "legendFormat": "replica"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 185 } },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 186 },
   "targets": [
    {
     "expr": "{app=\"mattermost\"} | json | plugin_id=\"com.mattermost.msteams-sync\" | level=\"error\""
    }
   ]
  }
 ]
}