{
 "title": "MS Teams (By Instance)",
 "description": "A dashboard for use with the Mattermost MSTeams Connect plugin.",
 "tags": [
  "mattermost",
  "msteams"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace" },
   {
    "name": "top_plugin_api_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(mattermost_plugin_api_time_count{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\"}[${__range_s}s])) by (api_name)))"
    }
   },
   {
    "name": "top_plugin_api_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(mattermost_plugin_api_time_sum{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\"}[${__range_s}s])) by (api_name) / sum(increase(mattermost_plugin_api_time_count{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\"}[${__range_s}s])) by (api_name)))"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "top_db_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_db_store_time_seconds_count{namespace=\"$namespace\"}[${__range_s}s])) by (method)))"
    }
   },
   {
    "name": "top_db_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_db_store_time_seconds_sum{namespace=\"$namespace\"}[${__range_s}s])) by (method) / sum(increase(msteams_connect_db_store_time_seconds_count{namespace=\"$namespace\"}[${__range_s}s])) by (method)))"
    }
   },
   {
    "name": "top_msgraph_client_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=\"$namespace\"}[${__range_s}s])) by (method)))"
    }
   },
   {
    "name": "top_msgraph_client_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=\"$namespace\"}[${__range_s}s])) by (method)))"
    }
   }
  ]
 },
 "panels": [
  { "title": "MS Teams Plugin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT COALESCE((SELECT name FROM installation WHERE id = '${namespace}' LIMIT 1), '${namespace}')"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 } },
  {
   "title": "Connected Users",
   "type": "stat",
   "description": "The total number of Mattermost users connected to MS Teams users.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_connected_users{namespace=~\"$namespace\"})",
     "legendFormat": "Connected Users"
    }
   ]
  },
  {
   "title": "Whitelist Limit",
   "type": "stat",
   "description": "The maximum number of Mattermost users allowed to connect to MS Teams.",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_whitelist_limit{namespace=~\"$namespace\"})",
     "legendFormat": "Connected Users"
    }
   ]
  },
  {
   "title": "Linked Channels",
   "type": "stat",
   "description": "The total number of linked channels to MS Teams.",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_linked_channels{namespace=~\"$namespace\"})",
     "legendFormat": "Linked Channels"
    }
   ]
  },
  {
   "title": "MS Teams Users",
   "type": "stat",
   "description": "The total number of MS Teams users detected upstream during the sync job.",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_upstream_users{namespace=~\"$namespace\"})",
     "legendFormat": "Linked Channels"
    }
   ]
  },
  {
   "title": "Synthetic Users",
   "type": "stat",
   "description": "The total number of synthetic users.",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_synthetic_users{namespace=~\"$namespace\"})",
     "legendFormat": "Synthetic Users"
    }
   ]
  },
  {
   "title": "Plugin Versions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "msteams_connect_system_plugin_info{namespace=~\"$namespace\",plugin=\"msteams\"} OR on() label_replace(vector(2), \"version\", \"<=1.5.3\", \"\", \"\")\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Client Secret Expiry",
   "type": "stat",
   "description": "When the application client secret expires.",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(msteams_connect_msgraph_client_secret_end_date_timestamp_seconds{namespace=~\"$namespace\",plugin=\"msteams\"}  * 1000)",
     "legendFormat": "Expiry Timestamp"
    }
   ]
  },
  {
   "title": "Client Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\",success!=\"true\"}[5m])) / sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\"}[5m])) or vector(0))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "DB Calls (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_db_store_time_seconds_count{namespace=~\"$namespace\"}[5m] offset 7d)) ",
     "legendFormat": "Last Week"
    },
    {
     "expr": "sum(rate(msteams_connect_db_store_time_seconds_count{namespace=~\"$namespace\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(msteams_connect_db_store_time_seconds_count{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "HTTP Requests (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_http_requests_total{namespace=~\"$namespace\"}[5m] offset 7d))",
     "legendFormat": "Last Week"
    },
    {
     "expr": "rate(msteams_connect_http_requests_total{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(msteams_connect_http_requests_total{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DB Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_db_store_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p99 ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_db_store_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p50 ({{instance}})"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_api_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p99 ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_api_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p50 ({{instance}})"
    }
   ]
  },
  {
   "title": "DB Calls by Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_db_store_time_seconds_count{namespace=\"$namespace\",method=~\"$top_db_count\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Requests by Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_api_time_seconds_count{namespace=~\"$namespace\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "DB calls by Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_db_store_time_seconds_sum{namespace=\"$namespace\",method=~\"$top_db_latency\"}[5m])) by (method) / sum(increase(msteams_connect_db_store_time_seconds_count{namespace=\"$namespace\",method=~\"$top_db_latency\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Requests by Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_api_time_seconds_sum{namespace=~\"$namespace\"}[5m])) by (handler) / sum(increase(msteams_connect_api_time_seconds_count{namespace=~\"$namespace\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Goroutine Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_system_plugin_goroutine_failures_total{namespace=\"$namespace\"}[5m])) by (instance) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_api_time_seconds_sum{namespace=~\"$namespace\",status_code!=\"200\",status_code!=\"202\",status_code!=\"303\",status_code!=\"304\"}[5m])) by (handler, status_code) / sum(increase(msteams_connect_api_time_seconds_count{namespace=~\"$namespace\",status_code!=\"200\",status_code!=\"202\",status_code!=\"303\",status_code!=\"304\"}[5m])) by (handler, status_code)",
     "legendFormat": "{{handler}} -- {{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Errors (per second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "rate(msteams_connect_http_errors_total{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(msteams_connect_http_errors_total{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(msteams_connect_http_errors_total{namespace=~\"$namespace\"}[5m] offset 7d))",
     "legendFormat": "Last Week"
    }
   ]
  },
  { "title": "MS Graph API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "MS Graph Client Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\"}[5m] offset 7d))",
     "legendFormat": "Last Week"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\"}[5m])) by (instance)",
     "legendFormat": "Requests ({{instance}})"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests (Errors Only)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\",success!=\"true\"}[5m])) by (instance)",
     "legendFormat": "Errors ({{instance}})"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\",success!=\"true\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\",success!=\"true\"}[5m] offset 7d))",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests by Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\",method=~\"$top_msgraph_client_count\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "MS Graph Client Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_msgraph_client_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p99 ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_msgraph_client_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p50 ({{instance}})"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests by Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_sum{namespace=~\"$namespace\",method=~\"$top_msgraph_client_latency\"}[5m])) by (method) / sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\",method=~\"$top_msgraph_client_latency\"}[5m])) by (method)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "MS Graph Client Error Rate",
   "type": "timeseries",
   "description": "Percentage of client requests failing.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\",success!=\"true\"}[5m])) / sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\"}[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalidated oAuth Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_oauth_token_invalidated_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Invalidated Tokens"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Change Event Queue",
   "type": "timeseries",
   "description": "The number of events currently in the change event queue and awaiting processing by an available goroutine, as well as the number of events rejected because the queue was full.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_app_change_event_queue_length{namespace=\"$namespace\"}[5m])) by (instance)",
     "legendFormat": "Length {{instance}}"
    },
    {
     "expr": "sum(increase(msteams_connect_events_change_event_queue_rejected_total{namespace=\"$namespace\"}[5m])) by (instance)",
     "legendFormat": "Rejected {{instance}}"
    }
   ]
  },
  {
   "title": "Processed Change Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_change_events_total{namespace=\"$namespace\",discarded_reason=\"\"}[5m])) by (change_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded Change Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 112 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_change_events_total{namespace=\"$namespace\",discarded_reason!=\"\"}[5m])) by (discarded_reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Events Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_change_events_total{namespace=\"$namespace\",discarded_reason=\"\"}[15m])) / sum(rate(msteams_connect_events_change_events_total{namespace=\"$namespace\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Lifecycle Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_lifecycle_events_total{namespace=\"$namespace\"}[5m])) by (event_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded Lifecycle Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 120 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_lifecycle_events_total{namespace=\"$namespace\",discarded_reason!=\"\"}[5m])) by (discarded_reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Events Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_lifecycle_events_total{namespace=\"$namespace\",discarded_reason=\"\"}[15m])) / sum(rate(msteams_connect_events_lifecycle_events_total{namespace=\"$namespace\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscriptions (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_subscriptions_total{namespace=\"$namespace\"}[5m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Messages (Mattermost -> MSTeams, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 136 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{namespace=\"$namespace\",source=\"mattermost\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{namespace=\"$namespace\",source=\"mattermost\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{namespace=\"$namespace\",source=\"mattermost\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Messages (MSTeams -> Mattermost, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 136 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{namespace=\"$namespace\",source=\"msteams\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{namespace=\"$namespace\",source=\"msteams\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_messages_total{namespace=\"$namespace\",source=\"msteams\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Reactions (Mattermost -> MSTeams, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{namespace=\"$namespace\",source=\"mattermost\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{namespace=\"$namespace\",source=\"mattermost\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{namespace=\"$namespace\",source=\"mattermost\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Reactions (MSTeams -> Mattermost, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{namespace=\"$namespace\",source=\"msteams\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{namespace=\"$namespace\",source=\"msteams\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_reactions_total{namespace=\"$namespace\",source=\"msteams\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Files (Mattermost -> MSTeams, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_files_total{namespace=\"$namespace\",source=\"mattermost\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_total{namespace=\"$namespace\",source=\"mattermost\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_total{namespace=\"$namespace\",source=\"mattermost\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  {
   "title": "Files (MSTeams -> Mattermost, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_files_total{namespace=\"$namespace\",source=\"msteams\",is_direct=\"true\"}[5m])) by (action)",
     "legendFormat": "Direct ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_total{namespace=\"$namespace\",source=\"msteams\",is_direct!=\"true\"}[5m])) by (action)",
     "legendFormat": "Channel ({{action}})"
    },
    {
     "expr": "sum(rate(msteams_connect_events_files_total{namespace=\"$namespace\",source=\"msteams\"}[5m])) by (action)",
     "legendFormat": "Total ({{action}})"
    }
   ]
  },
  { "title": "Shared Channels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 } },
  {
   "title": "Sync Msg Delay",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_shared_channels_sync_msg_post_delay_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (le))",
     "legendFormat": "Post Delay (p99)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_shared_channels_sync_msg_reaction_delay_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (le))",
     "legendFormat": "Reaction Delay (p99)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_shared_channels_sync_msg_file_delay_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (le))",
     "legendFormat": "File Delay (p99)"
    }
   ]
  },
  {
   "title": "Task Queue Size (Server-wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
   "targets": [
    {
     "expr": "mattermost_shared_channels_task_queue_size{namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task in Queue Duration (Server-wide)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mattermost_shared_channels_task_in_queue_duration_seconds_bucket{namespace=\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(mattermost_shared_channels_task_in_queue_duration_seconds_bucket{namespace=\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p50"
    }
   ]
  },
  { "title": "Plugin API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 } },
  {
   "title": "Top 10 Plugin API Requests by Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_plugin_api_time_count{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\",api_name=~\"$top_plugin_api_count\"}[5m])) by (api_name)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Top 10 Plugin API Requests by Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_plugin_api_time_sum{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\",api_name=~\"$top_plugin_api_latency\"}[5m])) by (api_name) / sum(increase(mattermost_plugin_api_time_count{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\",api_name=~\"$top_plugin_api_latency\"}[5m])) by (api_name)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"$namespace\",plugin=\"msteams\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(go_goroutines{namespace=~\"$namespace\",plugin=\"msteams\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Heap Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=~\"$namespace\",plugin=\"msteams\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 195 },
   "targets": [
    {
     "expr": "sum(msteams_connect_app_active_workers_total) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Workers Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_app_workers_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (worker,le))",
     "legendFormat": "{{worker}}, p99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_app_workers_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (worker,le))",
     "legendFormat": "{{worker}}, p50"
    }
   ]
  },
  {
   "title": "DB Connections (Whole Server)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mattermost_db_master_connections_total{namespace=\"${namespace}\"})",
     "legendFormat": "master"
    },
    {
     "expr": "sum(mattermost_db_read_replica_connections_total{namespace=\"${namespace}\"})",
     "legendFormat": "replica"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 211 } },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 212 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} | json | plugin_id=\"com.mattermost.msteams-sync\" | level=\"error\""
    }
   ]
  }
 ]
}