{
 "title": "MS Teams (By Instance), 1-way sync",
 "description": "A dashboard for use with the Mattermost MSTeams plugin.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": ".*" },
   {
    "name": "top_plugin_api_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(mattermost_plugin_api_time_count{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\"}[${__range_s}s])) by (api_name)))"
    }
   },
   {
    "name": "top_plugin_api_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(mattermost_plugin_api_time_sum{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\"}[${__range_s}s])) by (api_name) / sum(increase(mattermost_plugin_api_time_count{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\"}[${__range_s}s])) by (api_name)))"
    }
   },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "top_db_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_db_store_time_seconds_count{namespace=\"$namespace\"}[${__range_s}s])) by (method)))"
    }
   },
   {
    "name": "top_db_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_db_store_time_seconds_sum{namespace=\"$namespace\"}[${__range_s}s])) by (method) / sum(increase(msteams_connect_db_store_time_seconds_count{namespace=\"$namespace\"}[${__range_s}s])) by (method)))"
    }
   },
   {
    "name": "top_msgraph_client_count",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=\"$namespace\"}[${__range_s}s])) by (method)))"
    }
   },
   {
    "name": "top_msgraph_client_latency",
    "query": {
     "query": "query_result(topk(10, sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=\"$namespace\"}[${__range_s}s])) by (method)))"
    }
   }
  ]
 },
 "panels": [
  { "title": "MS Teams Plugin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Users",
   "type": "stat",
   "description": "The total number of Mattermost users who received at least one chat notification in the past 7 days.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_active_users_receiving{namespace=~\"$namespace\"})",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Connected Users",
   "type": "stat",
   "description": "The total number of Mattermost users connected to MS Teams users.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_connected_users{namespace=~\"$namespace\"})",
     "legendFormat": "Connected Users"
    }
   ]
  },
  {
   "title": "Invited Users",
   "type": "stat",
   "description": "The total number of Mattermost users invited to connect with MS Teams.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_pending_invites{namespace=~\"$namespace\"})",
     "legendFormat": "Invited Users"
    }
   ]
  },
  {
   "title": "Invites Limit",
   "type": "stat",
   "description": "The maximum number of pending connection invites.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_pending_invites_limit{namespace=~\"$namespace\"})",
     "legendFormat": "Invited Users"
    }
   ]
  },
  {
   "title": "Whitelisted Users",
   "type": "stat",
   "description": "The total number of Mattermost users authorized to connect at any time.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_whitelisted_users{namespace=~\"$namespace\"})",
     "legendFormat": "Whitelisted Users"
    }
   ]
  },
  {
   "title": "Max Connected",
   "type": "stat",
   "description": "The maximum number of Mattermost users allowed to connect to MS Teams.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(msteams_connect_app_connected_users_limit{namespace=~\"$namespace\"})",
     "legendFormat": "Whitelist Limit"
    }
   ]
  },
  {
   "title": "Client Secret Expiry",
   "type": "stat",
   "description": "When the application client secret expires.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(msteams_connect_msgraph_client_secret_end_date_timestamp_seconds{namespace=~\"$namespace\"}) - time()",
     "legendFormat": "Client Secret Expiry"
    }
   ]
  },
  {
   "title": "Plugin Versions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "msteams_connect_system_plugin_info{namespace=~\"$namespace\"} OR on() label_replace(vector(2), \"version\", \"<=1.5.3\", \"\", \"\")\n",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Client Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\",success!=\"true\"}[5m])) / sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\"}[5m])) or vector(0))",
     "legendFormat": "Client Success Rate"
    }
   ]
  },
  { "title": "Application", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "DB Calls (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_db_store_time_seconds_count{namespace=~\"$namespace\"}[5m] offset 7d)) ",
     "legendFormat": "Last Week"
    },
    {
     "expr": "sum(rate(msteams_connect_db_store_time_seconds_count{namespace=~\"$namespace\"}[5m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(msteams_connect_db_store_time_seconds_count{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "HTTP Requests (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_http_requests_total{namespace=~\"$namespace\"}[5m] offset 7d))",
     "legendFormat": "Last Week"
    },
    {
     "expr": "rate(msteams_connect_http_requests_total{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(msteams_connect_http_requests_total{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "DB Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_db_store_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p99 ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_db_store_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p50 ({{instance}})"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_api_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p99 ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_api_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p50 ({{instance}})"
    }
   ]
  },
  {
   "title": "DB Calls by Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_db_store_time_seconds_count{namespace=\"$namespace\",method=~\"$top_db_count\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Requests by Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_api_time_seconds_count{namespace=~\"$namespace\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "DB calls by Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_db_store_time_seconds_sum{namespace=\"$namespace\",method=~\"$top_db_latency\"}[5m])) by (method) / sum(increase(msteams_connect_db_store_time_seconds_count{namespace=\"$namespace\",method=~\"$top_db_latency\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "API Requests by Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_api_time_seconds_sum{namespace=~\"$namespace\"}[5m])) by (handler) / sum(increase(msteams_connect_api_time_seconds_count{namespace=~\"$namespace\"}[5m])) by (handler)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Goroutine Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_system_plugin_goroutine_failures_total{namespace=\"$namespace\"}[5m])) by (instance) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_api_time_seconds_sum{namespace=~\"$namespace\",status_code!=\"200\",status_code!=\"202\",status_code!=\"303\",status_code!=\"304\"}[5m])) by (handler, status_code) / sum(increase(msteams_connect_api_time_seconds_count{namespace=~\"$namespace\",status_code!=\"200\",status_code!=\"202\",status_code!=\"303\",status_code!=\"304\"}[5m])) by (handler, status_code)",
     "legendFormat": "{{handler}} -- {{status_code}}"
    }
   ]
  },
  {
   "title": "HTTP Errors (per second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "rate(msteams_connect_http_errors_total{namespace=~\"$namespace\"}[5m])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(rate(msteams_connect_http_errors_total{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(msteams_connect_http_errors_total{namespace=~\"$namespace\"}[5m] offset 7d))",
     "legendFormat": "Last Week"
    }
   ]
  },
  { "title": "MS Graph API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "MS Graph Client Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\"}[5m] offset 7d))",
     "legendFormat": "Last Week"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\"}[5m])) by (instance)",
     "legendFormat": "Requests ({{instance}})"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests (Errors Only)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\",success!=\"true\"}[5m])) by (instance)",
     "legendFormat": "Errors ({{instance}})"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\",success!=\"true\"}[5m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\",success!=\"true\"}[5m] offset 7d))",
     "legendFormat": "Last Week"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests by Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\",method=~\"$top_msgraph_client_count\"}[5m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "MS Graph Client Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_msgraph_client_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p99 ({{instance}})"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_msgraph_client_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (instance,le))",
     "legendFormat": "p50 ({{instance}})"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests by Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_sum{namespace=~\"$namespace\",method=~\"$top_msgraph_client_latency\"}[5m])) by (method) / sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\",method=~\"$top_msgraph_client_latency\"}[5m])) by (method)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "MS Graph Client Requests by Count (Errors Only)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\",success=\"false\"}[5m])) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalidated oAuth Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_oauth_token_invalidated_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Invalidated Tokens"
    }
   ]
  },
  {
   "title": "MS Graph Client Error Rate",
   "type": "timeseries",
   "description": "Percentage of client requests failing.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\",success!=\"true\"}[5m])) / sum(increase(msteams_connect_msgraph_client_time_seconds_count{namespace=~\"$namespace\"}[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Change Event Queue",
   "type": "timeseries",
   "description": "The number of events currently in the change event queue and awaiting processing by an available goroutine, as well as the number of events rejected because the queue was full.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "sum(increase(msteams_connect_app_change_event_queue_length{namespace=\"$namespace\"}[5m])) by (instance)",
     "legendFormat": "Length {{instance}}"
    },
    {
     "expr": "sum(increase(msteams_connect_events_change_event_queue_rejected_total{namespace=\"$namespace\"}[5m])) by (instance)",
     "legendFormat": "Rejected {{instance}}"
    }
   ]
  },
  {
   "title": "Processed Change Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_change_events_total{namespace=\"$namespace\",discarded_reason=\"\"}[5m])) by (change_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded Change Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 108 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_change_events_total{namespace=\"$namespace\",discarded_reason!=\"\"}[5m])) by (discarded_reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Events Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_change_events_total{namespace=\"$namespace\",discarded_reason=\"\"}[15m])) / sum(rate(msteams_connect_events_change_events_total{namespace=\"$namespace\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Lifecycle Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_lifecycle_events_total{namespace=\"$namespace\"}[5m])) by (event_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discarded Lifecycle Events (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 116 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_lifecycle_events_total{namespace=\"$namespace\",discarded_reason!=\"\"}[5m])) by (discarded_reason)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Events Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_lifecycle_events_total{namespace=\"$namespace\",discarded_reason=\"\"}[15m])) / sum(rate(msteams_connect_events_lifecycle_events_total{namespace=\"$namespace\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscriptions (per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 124 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_subscriptions_total{namespace=\"$namespace\"}[5m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Notifications (MSTeams -> Mattermost, per second)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 132 },
   "targets": [
    {
     "expr": "sum(rate(msteams_connect_events_notifications_total{namespace=\"$namespace\",is_group_chat=\"false\"}[5m])) by (action)",
     "legendFormat": "Chat"
    },
    {
     "expr": "sum(rate(msteams_connect_events_notifications_total{namespace=\"$namespace\",is_group_chat=\"true\"}[5m])) by (action)",
     "legendFormat": "Group"
    },
    {
     "expr": "sum(rate(msteams_connect_events_notifications_total{namespace=\"$namespace\"}[5m])) by (action)",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Plugin API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } },
  {
   "title": "Top 10 Plugin API Requests by Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_plugin_api_time_count{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\",api_name=~\"$top_plugin_api_count\"}[5m])) by (api_name)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Top 10 Plugin API Requests by Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(mattermost_plugin_api_time_sum{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\",api_name=~\"$top_plugin_api_latency\"}[5m])) by (api_name) / sum(increase(mattermost_plugin_api_time_count{namespace=~\"$namespace\",plugin_id=\"com.mattermost.msteams-sync\",api_name=~\"$top_plugin_api_latency\"}[5m])) by (api_name)",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 } },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"$namespace\",plugin=\"msteams\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(go_goroutines{namespace=~\"$namespace\",plugin=\"msteams\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Heap Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=~\"$namespace\",plugin=\"msteams\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "targets": [
    {
     "expr": "sum(msteams_connect_app_active_workers_total) by (worker)",
     "legendFormat": "{{worker}}"
    }
   ]
  },
  {
   "title": "Workers Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(msteams_connect_app_workers_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (worker,le))",
     "legendFormat": "{{worker}}, p99"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(msteams_connect_app_workers_time_seconds_bucket{namespace=~\"$namespace\"}[5m])) by (worker,le))",
     "legendFormat": "{{worker}}, p50"
    }
   ]
  },
  {
   "title": "DB Connections (Whole Server)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mattermost_db_master_connections_total{namespace=\"${namespace}\"})",
     "legendFormat": "master"
    },
    {
     "expr": "sum(mattermost_db_read_replica_connections_total{namespace=\"${namespace}\"})",
     "legendFormat": "replica"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 174 } },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 175 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\"} | json | plugin_id=\"com.mattermost.msteams-sync\" | level=\"error\""
    },
    {
     "expr": "{namespace=\"$namespace\"} | json | plugin_id=\"com.mattermost.msteams-sync\" | level=\"error\""
    }
   ]
  }
 ]
}