export const mockLinkedChannels = [

    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    }, {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },
    {
        msTeamsTeamID: 'string',
        msTeamsTeamName: 'string',
        msTeamsChannelID: 'string',
        msTeamsChannelName: 'string',
        mattermostTeamID: 'string',
        mattermostTeamName: 'string',
        mattermostChannelID: 'string',
        mattermostChannelName: 'string',
        mattermostChannelType: 'string',
        msTeamsChannelType: 'string',
    },

];
