name: ci
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:

permissions:
  contents: read

jobs:
  plugin-ci:
    uses: mattermost/actions-workflows/.github/workflows/plugin-ci.yml@8084e5bb4e1f54a939e1aeae83b44f2312d32c6e
    with:
      golangci-lint-version: "v1.54.2"
      golang-version: "1.21"
    secrets: inherit
